// <auto-generated />
using System;
using ColetaApi.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ColetaApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240625221803_01-Coleta")]
    partial class _01Coleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColetaApi.Models.ColetaModel", b =>
                {
                    b.Property<int>("Pk_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Pk_id"));

                    b.Property<string>("Ds_coleta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Ds_tipocoleta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("Dt_coleta")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Pk_id");

                    b.HasIndex("Ds_coleta");

                    b.ToTable("COLETA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
